EXE = 
LIB = liblogger.a
INCLUDE_DIRS = $(ROOT)/code/graphics/inc \
							 $(ROOT)/code/3dmath/inc \
							 $(ROOT)/code/logger/inc \
							 $(ROOT)/code/video/inc
ROOT = /e/sourceCode/poppy/poppy

include $(ROOT)/build/make.rule
