EXE = 
LIB = libutility.a
INCLUDE_DIRS = $(ROOT)/code/graphics/inc \
							 $(ROOT)/code/3dmath/inc \
							 $(ROOT)/code/logger/inc \
							 $(ROOT)/code/video/inc \
							 $(ROOT)/code/utility/inc

include $(ROOT)/build/make.rule
