EXE = 
LIB = libgraphics.a
INCLUDE_DIRS = $(ROOT)/code/graphics/inc \
							 $(ROOT)/code/3dmath/inc \
							 $(ROOT)/code/logger/inc \
							 $(ROOT)/code/video/inc

include $(ROOT)/build/make.rule
